---
nodejs_npm_global_packages:
  # A fully pluggable tool for identifying and reporting on patterns in JavaScript.
  # https://github.com/eslint/eslint
  - { name: eslint, state: present }
  - { name: node-sass, state: present }
  # A strongly-typed functional programming language that compiles to JavaScript
  # http://www.purescript.org/
  - { name: purescript, state: present }
  # A build tool for PureScript projects
  # https://github.com/purescript-contrib/pulp
  - { name: pulp, state: present }
  # The pluggable natural language linter for text and markdown.
  # https://github.com/textlint/textlint
  - { name: textlint, state: present }
  # JTFæ—¥æœ¬èªæ¨™æº–ã‚¹ã‚¿ã‚¤ãƒ«ã‚¬ã‚¤ãƒ‰ for textlint.
  # https://github.com/textlint-ja/textlint-rule-preset-JTF-style
  - { name: textlint-rule-preset-jtf-style, state: present }
  # TypeScript is a superset of JavaScript that compiles to clean JavaScript output.
  # https://github.com/Microsoft/TypeScript
  - { name: typescript, state: present }
  # CLI tool for running Yeoman generators
  # https://github.com/yeoman/yo
  - { name: yo, state: present }
  # Hubot generator for Yeoman
  # https://github.com/hubotio/generator-hubot#readme
  - { name: generator-hubot, state: present }
  # Find newer versions of package dependencies than what your package.json allows
  # https://www.npmjs.com/package/npm-check-updates
  - { name: npm-check-updates, state: present }
  # ğŸ¢ command line tool for blocking sites to be more productive
  # https://github.com/gorangajic/workmode
  - { name: workmode, state: present }

  # https://github.com/typicode/json-server
  # Get a full fake REST API with zero coding in less than 30 seconds (seriously)
  # Created with <3 for front-end developers who need a quick back-end for prototyping and mocking.
  - { name: json-graphql-server, state: present }

  # https://github.com/marmelab/json-graphql-server
  # Get a full fake GraphQL API with zero coding in less than 30 seconds.
  # Start playing with GraphQL right away with json-graphql-server, a testing and mocking tool for GraphQL. All it takes is a JSON of your data.
  # Inspired by the excellent json-server.
  - { name: json-graphql-server, state: present }
